// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _121220191354addminiheartquestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_121220191354addminiheartquestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201912120655151_12122019 1354 add miniheart question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
