// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _130820191004 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_130820191004));
        
        string IMigrationMetadata.Id
        {
            get { return "201908130304351_13082019 1004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
