// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _017720191559updatemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_017720191559updatemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201911070900366_017720191559 update model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
