// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _250420191405 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_250420191405));
        
        string IMigrationMetadata.Id
        {
            get { return "201904250705471_250420191405"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
