// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _020920191013addupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_020920191013addupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201909020314162_02092019 1013 add update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
