// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update070820191848addidquestionpes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update070820191848addidquestionpes));
        
        string IMigrationMetadata.Id
        {
            get { return "201908071149011_update070820191848 add id question pes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
