// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _021220191423dropandupdatemiiheart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_021220191423dropandupdatemiiheart));
        
        string IMigrationMetadata.Id
        {
            get { return "201912020723544_02122019 1423 drop and update miiheart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
