// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _061120191450addcolumnactioninprobationform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_061120191450addcolumnactioninprobationform));
        
        string IMigrationMetadata.Id
        {
            get { return "201911060751375_06112019 1450 add column action in probation form"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
