// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _14072201020addcanmaptopreetraineeform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14072201020addcanmaptopreetraineeform));
        
        string IMigrationMetadata.Id
        {
            get { return "202007140322180_1407220 1020 add can map to pree trainee form"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
