// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _040220201633addprobationwithout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_040220201633addprobationwithout));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041133355_04022020 1633  add probation with out"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
