// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatefixdatabas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatefixdatabas));
        
        string IMigrationMetadata.Id
        {
            get { return "202011300332492_update fix databas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
