// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _16072001443addactitiestocanmap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_16072001443addactitiestocanmap));
        
        string IMigrationMetadata.Id
        {
            get { return "202007160745524_1607200 1443 add actities to can map"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
