// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _150720200947addseqtorating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_150720200947addseqtorating));
        
        string IMigrationMetadata.Id
        {
            get { return "202007150248450_15072020 0947 add seq to rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
