// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _030820200959removeyear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_030820200959removeyear));
        
        string IMigrationMetadata.Id
        {
            get { return "202008030300255_03082020 0959 remove year"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
