// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2200920201352addcolumnforTM_Eva_Rating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2200920201352addcolumnforTM_Eva_Rating));
        
        string IMigrationMetadata.Id
        {
            get { return "202009220653414_220092020 1352 add column for TM_Eva_Rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
