// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _15072021251addactiitistoform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15072021251addactiitistoform));
        
        string IMigrationMetadata.Id
        {
            get { return "202007150552271_1507202 1251 addactiitis to form"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
