// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _13072021138addtm_activitis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13072021138addtm_activitis));
        
        string IMigrationMetadata.Id
        {
            get { return "202007130439169_1307202 1138 add tm_activitis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
