// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _14072021029updatcolumninpretraineeform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14072021029updatcolumninpretraineeform));
        
        string IMigrationMetadata.Id
        {
            get { return "202007140329517_1407202 1029 updat column in pretrainee form"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
