// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _100720201336addtalbeformdetailandratingforpretrainee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_100720201336addtalbeformdetailandratingforpretrainee));
        
        string IMigrationMetadata.Id
        {
            get { return "202007100637190_10072020 1336 add talbe form detail and rating for pretrainee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
