// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _140720201037updatepreetraieedetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_140720201037updatepreetraieedetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202007140337576_14072020 1037 update preetraiee detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
