// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMasterFKRatingtoCandidateMassTif : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMasterFKRatingtoCandidateMassTif));
        
        string IMigrationMetadata.Id
        {
            get { return "202009291039511_Add Master FK Rating to Candidate MassTif"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
