// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatecolGroupQuestinAuditQsAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecolGroupQuestinAuditQsAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "202010090902419_update col Group Questin Audit Qs Again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
