// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _30072201722addfkforTM_PES_NMN_SigntureStep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30072201722addfkforTM_PES_NMN_SigntureStep));
        
        string IMigrationMetadata.Id
        {
            get { return "202007301023195_3007220 1722 add fk for TM_PES_NMN_SigntureStep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
