// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _250120211634addcolumnforshownme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_250120211634addcolumnforshownme));
        
        string IMigrationMetadata.Id
        {
            get { return "202101250934563_25012021 1634 add column for show nme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
