// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_TablePrefixVisa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_TablePrefixVisa));
        
        string IMigrationMetadata.Id
        {
            get { return "202107020537213_update_Table Prefix Visa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
