// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _200120211108addminiheart2021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_200120211108addminiheart2021));
        
        string IMigrationMetadata.Id
        {
            get { return "202101200409138_20012021 1108 add miniheart2021 "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
