// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetblmstautomation_HrVisa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetblmstautomation_HrVisa));
        
        string IMigrationMetadata.Id
        {
            get { return "202109100312230_update tblmstautomation_HrVisa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
