// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdatedatabaseHCMHrTrackingVisadatabaseSSIS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedatabaseHCMHrTrackingVisadatabaseSSIS));
        
        string IMigrationMetadata.Id
        {
            get { return "202110110309488_Update database HCM Hr Tracking Visa database SSIS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
