// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changelimitofcreate_userandupdate_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changelimitofcreate_userandupdate_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202204250343144_change limit of create_user and update_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
