// <auto-generated />
namespace HumanCapitalManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeseqintm_consent_question : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeseqintm_consent_question));
        
        string IMigrationMetadata.Id
        {
            get { return "202204180840232_change seq in tm_consent_question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
