//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraineeManagement.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Employeeno { get; set; }
        public string Previous_EmployeeNo { get; set; }
        public string Prefix { get; set; }
        public string Employeename { get; set; }
        public string Employeemidname { get; set; }
        public string Employeesurname { get; set; }
        public string ThaiPrefix { get; set; }
        public string EmpThaiName { get; set; }
        public string EmpThaiMidName { get; set; }
        public string EmpThaiSurName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> StatusType { get; set; }
        public string RefID { get; set; }
        public string UserID { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Remark { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Sex { get; set; }
        public Nullable<bool> ActiveRetain { get; set; }
        public Nullable<System.DateTime> CalEleave { get; set; }
        public string Retain_Email { get; set; }
        public Nullable<int> GIS_Employment_Schedule { get; set; }
        public Nullable<System.DateTime> CreatedDate_Employee { get; set; }
        public Nullable<System.DateTime> UpdatedDate_Employee { get; set; }
        public string C_Status { get; set; }
        public string KPMG_USER_GPID { get; set; }
    }
}
