//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraineeManagement.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInfo
    {
        public string Employeeno { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Type { get; set; }
        public string Company { get; set; }
        public string Division { get; set; }
        public string Location { get; set; }
        public string Country { get; set; }
        public string EmpPosition { get; set; }
        public string LifeIns { get; set; }
        public string HealthIns { get; set; }
        public string Access { get; set; }
        public string Site { get; set; }
        public string Condition { get; set; }
        public string PF_Member { get; set; }
        public string PF { get; set; }
        public string PFPercent { get; set; }
        public string TaxStatus { get; set; }
        public string PI { get; set; }
        public string UnitGroup { get; set; }
        public string UnitGroup_IBS { get; set; }
        public string RankID { get; set; }
        public string Rank_IBS { get; set; }
        public string Pool { get; set; }
        public string Initial { get; set; }
        public string Editor { get; set; }
        public string YearHR { get; set; }
        public Nullable<int> RankHRID { get; set; }
        public Nullable<int> PositionHRID { get; set; }
        public string LE { get; set; }
        public string Approval1 { get; set; }
        public string Approval2 { get; set; }
        public string Approval3 { get; set; }
        public Nullable<int> VacLeaveLastYear { get; set; }
        public Nullable<int> EarnVacThisYear { get; set; }
        public string SubYear_HR { get; set; }
        public string Box9 { get; set; }
        public string DevelopPlan { get; set; }
        public Nullable<System.DateTime> OldJoinDate { get; set; }
        public string PerformanceMGCode { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string KPMG_User_GPID { get; set; }
        public Nullable<System.DateTime> CreatedDate_JobInfo { get; set; }
        public Nullable<System.DateTime> UpdatedDate_JobInfo { get; set; }
        public string Job { get; set; }
        public string CountryCompute { get; set; }
    }
}
