//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraineeManagement.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMaster_Unit
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public bool IsActive { get; set; }
        public int UnitGroupID { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbMaster_Company tbMaster_Company { get; set; }
        public virtual tbMaster_UnitGroup tbMaster_UnitGroup { get; set; }
    }
}
