//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraineeManagement.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMaster_RoleHead
    {
        public int RoleID { get; set; }
        public string EmployeeNo { get; set; }
        public int UnitGroupID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbMaster_Role tbMaster_Role { get; set; }
        public virtual tbMaster_UnitGroup tbMaster_UnitGroup { get; set; }
    }
}
