//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanCapitalManagement.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllInfo_WS
    {
        public string EmpNo { get; set; }
        public string UserID { get; set; }
        public string EmpTitle { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpMiddleName { get; set; }
        public string EmpSurname { get; set; }
        public string EmpFullName { get; set; }
        public string EmpName { get; set; }
        public string EmpThaiTitle { get; set; }
        public string EmpThaiFirstName { get; set; }
        public string EmpThaiSurName { get; set; }
        public string EmpThaiName { get; set; }
        public string Email { get; set; }
        public string CompanyCode { get; set; }
        public string PI { get; set; }
        public string Pool { get; set; }
        public string Division { get; set; }
        public string UnitGroup { get; set; }
        public string RankID { get; set; }
        public Nullable<int> RankHRID { get; set; }
        public string RankCode { get; set; }
        public string Rank { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Mobile { get; set; }
        public string OfficePhone { get; set; }
        public string Assistant { get; set; }
        public string AssistantName { get; set; }
        public string AssistantEmail { get; set; }
        public string Previous_EmployeeNo { get; set; }
        public Nullable<int> UnitGroupID { get; set; }
        public string UnitGroupName { get; set; }
        public Nullable<int> PoolID { get; set; }
        public string Company { get; set; }
        public string JobLevelText { get; set; }
    }
}
