//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanCapitalManagement.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StaffPhoto_FileName
    {
        public string Employeeno { get; set; }
        public string PhotoName { get; set; }
        public string Employeename { get; set; }
    }
}
