//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanCapitalManagement.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Unit
    {
        public int CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyShortName { get; set; }
        public string CompanyName { get; set; }
        public int PoolID { get; set; }
        public string PoolName { get; set; }
        public int UnitGroupID { get; set; }
        public string UnitGroupName { get; set; }
        public string UnitID { get; set; }
        public string UnitName { get; set; }
        public string CountryCode { get; set; }
        public bool IsActive { get; set; }
    }
}
