//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanCapitalManagement.Viztopia {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://th.kpmg.intranet/", ConfigurationName="Viztopia.ViztopiaSoap")]
    public interface ViztopiaSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (WS_AssignmentCodeDataSet_No_Parameter) of message WS_AssignmentCodeDataSet_No_Parameter does not match the default value (WS_AssignmentCodeDataSet)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_AssignmentCodeDataSet_No_Parameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter1 WS_AssignmentCodeDataSet(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_AssignmentCodeDataSet_No_Parameter", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter1> WS_AssignmentCodeDataSetAsync(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter request);
        
        // CODEGEN: Generating message contract since the wrapper name (WS_AssignmentCodeDataSet_With_Assignment_Code) of message WS_AssignmentCodeDataSet_With_Assignment_Code does not match the default value (WS_AssignmentCodeDataSet1)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_AssignmentCodeDataSet_With_Assignment_Code", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code1 WS_AssignmentCodeDataSet1(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_AssignmentCodeDataSet_With_Assignment_Code", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code1> WS_AssignmentCodeDataSet1Async(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code request);
        
        // CODEGEN: Generating message contract since the wrapper name (ClientList) of message ClientList does not match the default value (getAllClients)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ClientList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HumanCapitalManagement.Viztopia.ClientList1 getAllClients(HumanCapitalManagement.Viztopia.ClientList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.ClientList1> getAllClientsAsync(HumanCapitalManagement.Viztopia.ClientList request);
        
        // CODEGEN: Generating message contract since the wrapper name (ChargeCode) of message ChargeCode does not match the default value (getAllChargeCodes)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ChargeCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HumanCapitalManagement.Viztopia.ChargeCode1 getAllChargeCodes(HumanCapitalManagement.Viztopia.ChargeCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ChargeCode", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.ChargeCode1> getAllChargeCodesAsync(HumanCapitalManagement.Viztopia.ChargeCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/isActiveAssignment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int isActiveAssignment(string AssignmentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/isActiveAssignment", ReplyAction="*")]
        System.Threading.Tasks.Task<int> isActiveAssignmentAsync(string AssignmentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllEngagement(string Client, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagement", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllEngagementAsync(string Client, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ChargeCode_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ChargeCode_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ChargeCode_All", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ChargeCode_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ChargeCode_TH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ChargeCode_TH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/ChargeCode_TH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ChargeCode_THAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Get_Internal_Chargecode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Internal_Chargecode(string ChargeCodeDesc, string CompanyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Get_Internal_Chargecode", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Internal_ChargecodeAsync(string ChargeCodeDesc, string CompanyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Engagement_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_All", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Engagement_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/AllEngagement_TH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AllEngagement_TH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/AllEngagement_TH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AllEngagement_THAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (AllEngagement_TH_param) of message AllEngagement_TH_param does not match the default value (AllEngagement_TH1)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/AllEngagement_TH_param", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HumanCapitalManagement.Viztopia.AllEngagement_TH_param1 AllEngagement_TH1(HumanCapitalManagement.Viztopia.AllEngagement_TH_param request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/AllEngagement_TH_param", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.AllEngagement_TH_param1> AllEngagement_TH1Async(HumanCapitalManagement.Viztopia.AllEngagement_TH_param request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_TH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Engagement_TH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_TH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Engagement_THAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_LA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Engagement_LA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_LA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Engagement_LAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_MM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Engagement_MM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Engagement_MM", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Engagement_MMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Client_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_All", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Client_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_TH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Client_TH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_TH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Client_THAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_LA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Client_LA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_LA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Client_LAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_MM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Client_MM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Client_MM", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Client_MMAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (GetAllEngagementFromSSIS) of message GetAllEngagementFromSSIS does not match the default value (GetAllEngagementFromSSA)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagementFromSSIS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS1 GetAllEngagementFromSSA(HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagementFromSSIS", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS1> GetAllEngagementFromSSAAsync(HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagementDetailFromSSA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllEngagementDetailFromSSA(string EngagementNo, string ClientNo, string ClientName, string EngagementStatusId, string FunctionId, string ProfitCentreNo, string CompanyCode, string EngagementTypeId, string Employeeno, string EngagementManagerNo, string EngagementPartnerNo, string SigningPartnerNo, string EngagementEQCRNo, string CreateYearStart, string YearEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagementDetailFromSSA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllEngagementDetailFromSSAAsync(string EngagementNo, string ClientNo, string ClientName, string EngagementStatusId, string FunctionId, string ProfitCentreNo, string CompanyCode, string EngagementTypeId, string Employeeno, string EngagementManagerNo, string EngagementPartnerNo, string SigningPartnerNo, string EngagementEQCRNo, string CreateYearStart, string YearEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagementDetailFromSSA_WColumn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllEngagementDetailFromSSA_WColumn(
                    string EngagementNo, 
                    string ClientNo, 
                    string ClientName, 
                    string EngagementStatusId, 
                    string FunctionId, 
                    string ProfitCentreNo, 
                    string CompanyCode, 
                    string EngagementTypeId, 
                    string Employeeno, 
                    string EngagementManagerNo, 
                    string EngagementPartnerNo, 
                    string SigningPartnerNo, 
                    string EngagementEQCRNo, 
                    string CreateYearStart, 
                    string YearEnd, 
                    string ColumnName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllEngagementDetailFromSSA_WColumn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllEngagementDetailFromSSA_WColumnAsync(
                    string EngagementNo, 
                    string ClientNo, 
                    string ClientName, 
                    string EngagementStatusId, 
                    string FunctionId, 
                    string ProfitCentreNo, 
                    string CompanyCode, 
                    string EngagementTypeId, 
                    string Employeeno, 
                    string EngagementManagerNo, 
                    string EngagementPartnerNo, 
                    string SigningPartnerNo, 
                    string EngagementEQCRNo, 
                    string CreateYearStart, 
                    string YearEnd, 
                    string ColumnName);
        
        // CODEGEN: Generating message contract since the wrapper name (GetAllClientFromSSIS) of message GetAllClientFromSSIS does not match the default value (GetAllClientFromSSA)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllClientFromSSIS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HumanCapitalManagement.Viztopia.GetAllClientFromSSIS1 GetAllClientFromSSA(HumanCapitalManagement.Viztopia.GetAllClientFromSSIS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/GetAllClientFromSSIS", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.GetAllClientFromSSIS1> GetAllClientFromSSAAsync(HumanCapitalManagement.Viztopia.GetAllClientFromSSIS request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_AssignmentCodeDataSet_No_Parameter", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_AssignmentCodeDataSet_No_Parameter {
        
        public WS_AssignmentCodeDataSet_No_Parameter() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_AssignmentCodeDataSet_No_ParameterResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_AssignmentCodeDataSet_No_Parameter1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet WS_AssignmentCodeDataSet_No_ParameterResult;
        
        public WS_AssignmentCodeDataSet_No_Parameter1() {
        }
        
        public WS_AssignmentCodeDataSet_No_Parameter1(System.Data.DataSet WS_AssignmentCodeDataSet_No_ParameterResult) {
            this.WS_AssignmentCodeDataSet_No_ParameterResult = WS_AssignmentCodeDataSet_No_ParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_AssignmentCodeDataSet_With_Assignment_Code", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_AssignmentCodeDataSet_With_Assignment_Code {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public string AssignmentCode;
        
        public WS_AssignmentCodeDataSet_With_Assignment_Code() {
        }
        
        public WS_AssignmentCodeDataSet_With_Assignment_Code(string AssignmentCode) {
            this.AssignmentCode = AssignmentCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_AssignmentCodeDataSet_With_Assignment_CodeResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_AssignmentCodeDataSet_With_Assignment_Code1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet WS_AssignmentCodeDataSet_With_Assignment_CodeResult;
        
        public WS_AssignmentCodeDataSet_With_Assignment_Code1() {
        }
        
        public WS_AssignmentCodeDataSet_With_Assignment_Code1(System.Data.DataSet WS_AssignmentCodeDataSet_With_Assignment_CodeResult) {
            this.WS_AssignmentCodeDataSet_With_Assignment_CodeResult = WS_AssignmentCodeDataSet_With_Assignment_CodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientList", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class ClientList {
        
        public ClientList() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientListResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class ClientList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet ClientListResult;
        
        public ClientList1() {
        }
        
        public ClientList1(System.Data.DataSet ClientListResult) {
            this.ClientListResult = ClientListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeCode", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class ChargeCode {
        
        public ChargeCode() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeCodeResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class ChargeCode1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet ChargeCodeResult;
        
        public ChargeCode1() {
        }
        
        public ChargeCode1(System.Data.DataSet ChargeCodeResult) {
            this.ChargeCodeResult = ChargeCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllEngagement_TH_param", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class AllEngagement_TH_param {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public string column;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=1)]
        public string filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=2)]
        public string sort;
        
        public AllEngagement_TH_param() {
        }
        
        public AllEngagement_TH_param(string column, string filter, string sort) {
            this.column = column;
            this.filter = filter;
            this.sort = sort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllEngagement_TH_paramResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class AllEngagement_TH_param1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet AllEngagement_TH_paramResult;
        
        public AllEngagement_TH_param1() {
        }
        
        public AllEngagement_TH_param1(System.Data.DataSet AllEngagement_TH_paramResult) {
            this.AllEngagement_TH_paramResult = AllEngagement_TH_paramResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllEngagementFromSSIS", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class GetAllEngagementFromSSIS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public string ClientNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=1)]
        public string ClientName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=2)]
        public string EngagementStatusId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=3)]
        public string FunctionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=4)]
        public string ProfitCentreNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=5)]
        public string CompanyCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=6)]
        public string EngagementTypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=7)]
        public string Employeeno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=8)]
        public string EngagementManagerNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=9)]
        public string EngagementPartnerNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=10)]
        public string CreateYearStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=11)]
        public string YearEnd;
        
        public GetAllEngagementFromSSIS() {
        }
        
        public GetAllEngagementFromSSIS(string ClientNo, string ClientName, string EngagementStatusId, string FunctionId, string ProfitCentreNo, string CompanyCode, string EngagementTypeId, string Employeeno, string EngagementManagerNo, string EngagementPartnerNo, string CreateYearStart, string YearEnd) {
            this.ClientNo = ClientNo;
            this.ClientName = ClientName;
            this.EngagementStatusId = EngagementStatusId;
            this.FunctionId = FunctionId;
            this.ProfitCentreNo = ProfitCentreNo;
            this.CompanyCode = CompanyCode;
            this.EngagementTypeId = EngagementTypeId;
            this.Employeeno = Employeeno;
            this.EngagementManagerNo = EngagementManagerNo;
            this.EngagementPartnerNo = EngagementPartnerNo;
            this.CreateYearStart = CreateYearStart;
            this.YearEnd = YearEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllEngagementFromSSISResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class GetAllEngagementFromSSIS1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataTable GetAllEngagementFromSSISResult;
        
        public GetAllEngagementFromSSIS1() {
        }
        
        public GetAllEngagementFromSSIS1(System.Data.DataTable GetAllEngagementFromSSISResult) {
            this.GetAllEngagementFromSSISResult = GetAllEngagementFromSSISResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllClientFromSSIS", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class GetAllClientFromSSIS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public string ClientNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=1)]
        public string ClientGroupNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=2)]
        public string GisNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=3)]
        public string DirectParentNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=4)]
        public string GlobalUltimateParentNo;
        
        public GetAllClientFromSSIS() {
        }
        
        public GetAllClientFromSSIS(string ClientNo, string ClientGroupNo, string GisNo, string DirectParentNo, string GlobalUltimateParentNo) {
            this.ClientNo = ClientNo;
            this.ClientGroupNo = ClientGroupNo;
            this.GisNo = GisNo;
            this.DirectParentNo = DirectParentNo;
            this.GlobalUltimateParentNo = GlobalUltimateParentNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllClientFromSSISResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class GetAllClientFromSSIS1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataTable GetAllClientFromSSISResult;
        
        public GetAllClientFromSSIS1() {
        }
        
        public GetAllClientFromSSIS1(System.Data.DataTable GetAllClientFromSSISResult) {
            this.GetAllClientFromSSISResult = GetAllClientFromSSISResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViztopiaSoapChannel : HumanCapitalManagement.Viztopia.ViztopiaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViztopiaSoapClient : System.ServiceModel.ClientBase<HumanCapitalManagement.Viztopia.ViztopiaSoap>, HumanCapitalManagement.Viztopia.ViztopiaSoap {
        
        public ViztopiaSoapClient() {
        }
        
        public ViztopiaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViztopiaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViztopiaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViztopiaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter1 HumanCapitalManagement.Viztopia.ViztopiaSoap.WS_AssignmentCodeDataSet(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter request) {
            return base.Channel.WS_AssignmentCodeDataSet(request);
        }
        
        public System.Data.DataSet WS_AssignmentCodeDataSet() {
            HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter inValue = new HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter();
            HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter1 retVal = ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).WS_AssignmentCodeDataSet(inValue);
            return retVal.WS_AssignmentCodeDataSet_No_ParameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter1> HumanCapitalManagement.Viztopia.ViztopiaSoap.WS_AssignmentCodeDataSetAsync(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter request) {
            return base.Channel.WS_AssignmentCodeDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter1> WS_AssignmentCodeDataSetAsync() {
            HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter inValue = new HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_No_Parameter();
            return ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).WS_AssignmentCodeDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code1 HumanCapitalManagement.Viztopia.ViztopiaSoap.WS_AssignmentCodeDataSet1(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code request) {
            return base.Channel.WS_AssignmentCodeDataSet1(request);
        }
        
        public System.Data.DataSet WS_AssignmentCodeDataSet1(string AssignmentCode) {
            HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code inValue = new HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code();
            inValue.AssignmentCode = AssignmentCode;
            HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code1 retVal = ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).WS_AssignmentCodeDataSet1(inValue);
            return retVal.WS_AssignmentCodeDataSet_With_Assignment_CodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code1> HumanCapitalManagement.Viztopia.ViztopiaSoap.WS_AssignmentCodeDataSet1Async(HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code request) {
            return base.Channel.WS_AssignmentCodeDataSet1Async(request);
        }
        
        public System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code1> WS_AssignmentCodeDataSet1Async(string AssignmentCode) {
            HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code inValue = new HumanCapitalManagement.Viztopia.WS_AssignmentCodeDataSet_With_Assignment_Code();
            inValue.AssignmentCode = AssignmentCode;
            return ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).WS_AssignmentCodeDataSet1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanCapitalManagement.Viztopia.ClientList1 HumanCapitalManagement.Viztopia.ViztopiaSoap.getAllClients(HumanCapitalManagement.Viztopia.ClientList request) {
            return base.Channel.getAllClients(request);
        }
        
        public System.Data.DataSet getAllClients() {
            HumanCapitalManagement.Viztopia.ClientList inValue = new HumanCapitalManagement.Viztopia.ClientList();
            HumanCapitalManagement.Viztopia.ClientList1 retVal = ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).getAllClients(inValue);
            return retVal.ClientListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.ClientList1> HumanCapitalManagement.Viztopia.ViztopiaSoap.getAllClientsAsync(HumanCapitalManagement.Viztopia.ClientList request) {
            return base.Channel.getAllClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.ClientList1> getAllClientsAsync() {
            HumanCapitalManagement.Viztopia.ClientList inValue = new HumanCapitalManagement.Viztopia.ClientList();
            return ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).getAllClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanCapitalManagement.Viztopia.ChargeCode1 HumanCapitalManagement.Viztopia.ViztopiaSoap.getAllChargeCodes(HumanCapitalManagement.Viztopia.ChargeCode request) {
            return base.Channel.getAllChargeCodes(request);
        }
        
        public System.Data.DataSet getAllChargeCodes() {
            HumanCapitalManagement.Viztopia.ChargeCode inValue = new HumanCapitalManagement.Viztopia.ChargeCode();
            HumanCapitalManagement.Viztopia.ChargeCode1 retVal = ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).getAllChargeCodes(inValue);
            return retVal.ChargeCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.ChargeCode1> HumanCapitalManagement.Viztopia.ViztopiaSoap.getAllChargeCodesAsync(HumanCapitalManagement.Viztopia.ChargeCode request) {
            return base.Channel.getAllChargeCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.ChargeCode1> getAllChargeCodesAsync() {
            HumanCapitalManagement.Viztopia.ChargeCode inValue = new HumanCapitalManagement.Viztopia.ChargeCode();
            return ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).getAllChargeCodesAsync(inValue);
        }
        
        public int isActiveAssignment(string AssignmentCode) {
            return base.Channel.isActiveAssignment(AssignmentCode);
        }
        
        public System.Threading.Tasks.Task<int> isActiveAssignmentAsync(string AssignmentCode) {
            return base.Channel.isActiveAssignmentAsync(AssignmentCode);
        }
        
        public System.Data.DataTable GetAllEngagement(string Client, string Status) {
            return base.Channel.GetAllEngagement(Client, Status);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllEngagementAsync(string Client, string Status) {
            return base.Channel.GetAllEngagementAsync(Client, Status);
        }
        
        public System.Data.DataSet ChargeCode_All() {
            return base.Channel.ChargeCode_All();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ChargeCode_AllAsync() {
            return base.Channel.ChargeCode_AllAsync();
        }
        
        public System.Data.DataSet ChargeCode_TH() {
            return base.Channel.ChargeCode_TH();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ChargeCode_THAsync() {
            return base.Channel.ChargeCode_THAsync();
        }
        
        public System.Data.DataSet Get_Internal_Chargecode(string ChargeCodeDesc, string CompanyName) {
            return base.Channel.Get_Internal_Chargecode(ChargeCodeDesc, CompanyName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Internal_ChargecodeAsync(string ChargeCodeDesc, string CompanyName) {
            return base.Channel.Get_Internal_ChargecodeAsync(ChargeCodeDesc, CompanyName);
        }
        
        public System.Data.DataSet Engagement_All() {
            return base.Channel.Engagement_All();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Engagement_AllAsync() {
            return base.Channel.Engagement_AllAsync();
        }
        
        public System.Data.DataSet AllEngagement_TH() {
            return base.Channel.AllEngagement_TH();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AllEngagement_THAsync() {
            return base.Channel.AllEngagement_THAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanCapitalManagement.Viztopia.AllEngagement_TH_param1 HumanCapitalManagement.Viztopia.ViztopiaSoap.AllEngagement_TH1(HumanCapitalManagement.Viztopia.AllEngagement_TH_param request) {
            return base.Channel.AllEngagement_TH1(request);
        }
        
        public System.Data.DataSet AllEngagement_TH1(string column, string filter, string sort) {
            HumanCapitalManagement.Viztopia.AllEngagement_TH_param inValue = new HumanCapitalManagement.Viztopia.AllEngagement_TH_param();
            inValue.column = column;
            inValue.filter = filter;
            inValue.sort = sort;
            HumanCapitalManagement.Viztopia.AllEngagement_TH_param1 retVal = ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).AllEngagement_TH1(inValue);
            return retVal.AllEngagement_TH_paramResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.AllEngagement_TH_param1> HumanCapitalManagement.Viztopia.ViztopiaSoap.AllEngagement_TH1Async(HumanCapitalManagement.Viztopia.AllEngagement_TH_param request) {
            return base.Channel.AllEngagement_TH1Async(request);
        }
        
        public System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.AllEngagement_TH_param1> AllEngagement_TH1Async(string column, string filter, string sort) {
            HumanCapitalManagement.Viztopia.AllEngagement_TH_param inValue = new HumanCapitalManagement.Viztopia.AllEngagement_TH_param();
            inValue.column = column;
            inValue.filter = filter;
            inValue.sort = sort;
            return ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).AllEngagement_TH1Async(inValue);
        }
        
        public System.Data.DataSet Engagement_TH() {
            return base.Channel.Engagement_TH();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Engagement_THAsync() {
            return base.Channel.Engagement_THAsync();
        }
        
        public System.Data.DataSet Engagement_LA() {
            return base.Channel.Engagement_LA();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Engagement_LAAsync() {
            return base.Channel.Engagement_LAAsync();
        }
        
        public System.Data.DataSet Engagement_MM() {
            return base.Channel.Engagement_MM();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Engagement_MMAsync() {
            return base.Channel.Engagement_MMAsync();
        }
        
        public System.Data.DataSet Client_All() {
            return base.Channel.Client_All();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Client_AllAsync() {
            return base.Channel.Client_AllAsync();
        }
        
        public System.Data.DataSet Client_TH() {
            return base.Channel.Client_TH();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Client_THAsync() {
            return base.Channel.Client_THAsync();
        }
        
        public System.Data.DataSet Client_LA() {
            return base.Channel.Client_LA();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Client_LAAsync() {
            return base.Channel.Client_LAAsync();
        }
        
        public System.Data.DataSet Client_MM() {
            return base.Channel.Client_MM();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Client_MMAsync() {
            return base.Channel.Client_MMAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS1 HumanCapitalManagement.Viztopia.ViztopiaSoap.GetAllEngagementFromSSA(HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS request) {
            return base.Channel.GetAllEngagementFromSSA(request);
        }
        
        public System.Data.DataTable GetAllEngagementFromSSA(string ClientNo, string ClientName, string EngagementStatusId, string FunctionId, string ProfitCentreNo, string CompanyCode, string EngagementTypeId, string Employeeno, string EngagementManagerNo, string EngagementPartnerNo, string CreateYearStart, string YearEnd) {
            HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS inValue = new HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS();
            inValue.ClientNo = ClientNo;
            inValue.ClientName = ClientName;
            inValue.EngagementStatusId = EngagementStatusId;
            inValue.FunctionId = FunctionId;
            inValue.ProfitCentreNo = ProfitCentreNo;
            inValue.CompanyCode = CompanyCode;
            inValue.EngagementTypeId = EngagementTypeId;
            inValue.Employeeno = Employeeno;
            inValue.EngagementManagerNo = EngagementManagerNo;
            inValue.EngagementPartnerNo = EngagementPartnerNo;
            inValue.CreateYearStart = CreateYearStart;
            inValue.YearEnd = YearEnd;
            HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS1 retVal = ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).GetAllEngagementFromSSA(inValue);
            return retVal.GetAllEngagementFromSSISResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS1> HumanCapitalManagement.Viztopia.ViztopiaSoap.GetAllEngagementFromSSAAsync(HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS request) {
            return base.Channel.GetAllEngagementFromSSAAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS1> GetAllEngagementFromSSAAsync(string ClientNo, string ClientName, string EngagementStatusId, string FunctionId, string ProfitCentreNo, string CompanyCode, string EngagementTypeId, string Employeeno, string EngagementManagerNo, string EngagementPartnerNo, string CreateYearStart, string YearEnd) {
            HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS inValue = new HumanCapitalManagement.Viztopia.GetAllEngagementFromSSIS();
            inValue.ClientNo = ClientNo;
            inValue.ClientName = ClientName;
            inValue.EngagementStatusId = EngagementStatusId;
            inValue.FunctionId = FunctionId;
            inValue.ProfitCentreNo = ProfitCentreNo;
            inValue.CompanyCode = CompanyCode;
            inValue.EngagementTypeId = EngagementTypeId;
            inValue.Employeeno = Employeeno;
            inValue.EngagementManagerNo = EngagementManagerNo;
            inValue.EngagementPartnerNo = EngagementPartnerNo;
            inValue.CreateYearStart = CreateYearStart;
            inValue.YearEnd = YearEnd;
            return ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).GetAllEngagementFromSSAAsync(inValue);
        }
        
        public System.Data.DataTable GetAllEngagementDetailFromSSA(string EngagementNo, string ClientNo, string ClientName, string EngagementStatusId, string FunctionId, string ProfitCentreNo, string CompanyCode, string EngagementTypeId, string Employeeno, string EngagementManagerNo, string EngagementPartnerNo, string SigningPartnerNo, string EngagementEQCRNo, string CreateYearStart, string YearEnd) {
            return base.Channel.GetAllEngagementDetailFromSSA(EngagementNo, ClientNo, ClientName, EngagementStatusId, FunctionId, ProfitCentreNo, CompanyCode, EngagementTypeId, Employeeno, EngagementManagerNo, EngagementPartnerNo, SigningPartnerNo, EngagementEQCRNo, CreateYearStart, YearEnd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllEngagementDetailFromSSAAsync(string EngagementNo, string ClientNo, string ClientName, string EngagementStatusId, string FunctionId, string ProfitCentreNo, string CompanyCode, string EngagementTypeId, string Employeeno, string EngagementManagerNo, string EngagementPartnerNo, string SigningPartnerNo, string EngagementEQCRNo, string CreateYearStart, string YearEnd) {
            return base.Channel.GetAllEngagementDetailFromSSAAsync(EngagementNo, ClientNo, ClientName, EngagementStatusId, FunctionId, ProfitCentreNo, CompanyCode, EngagementTypeId, Employeeno, EngagementManagerNo, EngagementPartnerNo, SigningPartnerNo, EngagementEQCRNo, CreateYearStart, YearEnd);
        }
        
        public System.Data.DataTable GetAllEngagementDetailFromSSA_WColumn(
                    string EngagementNo, 
                    string ClientNo, 
                    string ClientName, 
                    string EngagementStatusId, 
                    string FunctionId, 
                    string ProfitCentreNo, 
                    string CompanyCode, 
                    string EngagementTypeId, 
                    string Employeeno, 
                    string EngagementManagerNo, 
                    string EngagementPartnerNo, 
                    string SigningPartnerNo, 
                    string EngagementEQCRNo, 
                    string CreateYearStart, 
                    string YearEnd, 
                    string ColumnName) {
            return base.Channel.GetAllEngagementDetailFromSSA_WColumn(EngagementNo, ClientNo, ClientName, EngagementStatusId, FunctionId, ProfitCentreNo, CompanyCode, EngagementTypeId, Employeeno, EngagementManagerNo, EngagementPartnerNo, SigningPartnerNo, EngagementEQCRNo, CreateYearStart, YearEnd, ColumnName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllEngagementDetailFromSSA_WColumnAsync(
                    string EngagementNo, 
                    string ClientNo, 
                    string ClientName, 
                    string EngagementStatusId, 
                    string FunctionId, 
                    string ProfitCentreNo, 
                    string CompanyCode, 
                    string EngagementTypeId, 
                    string Employeeno, 
                    string EngagementManagerNo, 
                    string EngagementPartnerNo, 
                    string SigningPartnerNo, 
                    string EngagementEQCRNo, 
                    string CreateYearStart, 
                    string YearEnd, 
                    string ColumnName) {
            return base.Channel.GetAllEngagementDetailFromSSA_WColumnAsync(EngagementNo, ClientNo, ClientName, EngagementStatusId, FunctionId, ProfitCentreNo, CompanyCode, EngagementTypeId, Employeeno, EngagementManagerNo, EngagementPartnerNo, SigningPartnerNo, EngagementEQCRNo, CreateYearStart, YearEnd, ColumnName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanCapitalManagement.Viztopia.GetAllClientFromSSIS1 HumanCapitalManagement.Viztopia.ViztopiaSoap.GetAllClientFromSSA(HumanCapitalManagement.Viztopia.GetAllClientFromSSIS request) {
            return base.Channel.GetAllClientFromSSA(request);
        }
        
        public System.Data.DataTable GetAllClientFromSSA(string ClientNo, string ClientGroupNo, string GisNo, string DirectParentNo, string GlobalUltimateParentNo) {
            HumanCapitalManagement.Viztopia.GetAllClientFromSSIS inValue = new HumanCapitalManagement.Viztopia.GetAllClientFromSSIS();
            inValue.ClientNo = ClientNo;
            inValue.ClientGroupNo = ClientGroupNo;
            inValue.GisNo = GisNo;
            inValue.DirectParentNo = DirectParentNo;
            inValue.GlobalUltimateParentNo = GlobalUltimateParentNo;
            HumanCapitalManagement.Viztopia.GetAllClientFromSSIS1 retVal = ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).GetAllClientFromSSA(inValue);
            return retVal.GetAllClientFromSSISResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.GetAllClientFromSSIS1> HumanCapitalManagement.Viztopia.ViztopiaSoap.GetAllClientFromSSAAsync(HumanCapitalManagement.Viztopia.GetAllClientFromSSIS request) {
            return base.Channel.GetAllClientFromSSAAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanCapitalManagement.Viztopia.GetAllClientFromSSIS1> GetAllClientFromSSAAsync(string ClientNo, string ClientGroupNo, string GisNo, string DirectParentNo, string GlobalUltimateParentNo) {
            HumanCapitalManagement.Viztopia.GetAllClientFromSSIS inValue = new HumanCapitalManagement.Viztopia.GetAllClientFromSSIS();
            inValue.ClientNo = ClientNo;
            inValue.ClientGroupNo = ClientGroupNo;
            inValue.GisNo = GisNo;
            inValue.DirectParentNo = DirectParentNo;
            inValue.GlobalUltimateParentNo = GlobalUltimateParentNo;
            return ((HumanCapitalManagement.Viztopia.ViztopiaSoap)(this)).GetAllClientFromSSAAsync(inValue);
        }
    }
}
