//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraineeManagement.wsHRIS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://th.kpmg.intranet/", ConfigurationName="wsHRIS.HRISSoap")]
    public interface HRISSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getEmployeeInfo(string empIdType, string empId, string active, string pool, string pi, string comp, string rank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoAsync(string empIdType, string empId, string active, string pool, string pi, string comp, string rank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getCustomEmployeeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getCustomEmployeeInfo(string empIdType, string empId, string active, string pool, string pi, string comp, string rank, string unitgroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getCustomEmployeeInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getCustomEmployeeInfoAsync(string empIdType, string empId, string active, string pool, string pi, string comp, string rank, string unitgroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllActiveStaff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllActiveStaff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllActiveStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllActiveStaffAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllStaff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllStaff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllStaffAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getActiveStaffByEmpNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getActiveStaffByEmpNo(string empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getActiveStaffByEmpNo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getActiveStaffByEmpNoAsync(string empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getActiveStaffByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getActiveStaffByUserID(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getActiveStaffByUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getActiveStaffByUserIDAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfoByEmpNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getEmployeeInfoByEmpNo(string empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfoByEmpNo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoByEmpNoAsync(string empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfoByEmpNoMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getEmployeeInfoByEmpNoMultiple(string empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfoByEmpNoMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoByEmpNoMultipleAsync(string empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfoByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getEmployeeInfoByUserID(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeInfoByUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoByUserIDAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeNoByUname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getEmployeeNoByUname(string uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeNoByUname", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getEmployeeNoByUnameAsync(string uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getEmployeeName(string empIdType, string empId, bool middlename, bool prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getEmployeeNameAsync(string empIdType, string empId, bool middlename, bool prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getEmployeeEmail(string empIdType, string empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getEmployeeEmailAsync(string empIdType, string empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getUserIDByEmployeeNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getUserIDByEmployeeNo(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getUserIDByEmployeeNo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getUserIDByEmployeeNoAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeNoByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getEmployeeNoByUserID(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getEmployeeNoByUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getEmployeeNoByUserIDAsync(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/isActiveEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int isActiveEmployee(string empIdType, string empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/isActiveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<int> isActiveEmployeeAsync(string empIdType, string empId);
        
        // CODEGEN: Generating message contract since the wrapper name (WS_GetEmployeeDetailDataSet_No_Parameter) of message WS_GetEmployeeDetailDataSet_No_Parameter does not match the default value (WS_GetEmployeeDetailDataSet)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_GetEmployeeDetailDataSet_No_Parameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter1 WS_GetEmployeeDetailDataSet(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_GetEmployeeDetailDataSet_No_Parameter", ReplyAction="*")]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter1> WS_GetEmployeeDetailDataSetAsync(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter request);
        
        // CODEGEN: Generating message contract since the wrapper name (WS_GetEmployeeDetailDataSet_With_Parameter) of message WS_GetEmployeeDetailDataSet_With_Parameter does not match the default value (WS_GetEmployeeDetailDataSet1)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_GetEmployeeDetailDataSet_With_Parameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter1 WS_GetEmployeeDetailDataSet1(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_GetEmployeeDetailDataSet_With_Parameter", ReplyAction="*")]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter1> WS_GetEmployeeDetailDataSet1Async(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_CheckActiveUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WS_CheckActiveUser(string Param, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/WS_CheckActiveUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WS_CheckActiveUserAsync(string Param, string Type);
        
        // CODEGEN: Generating message contract since the wrapper name (CompanyList) of message CompanyList does not match the default value (getCompany)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/CompanyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraineeManagement.wsHRIS.CompanyList1 getCompany(TraineeManagement.wsHRIS.CompanyList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/CompanyList", ReplyAction="*")]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.CompanyList1> getCompanyAsync(TraineeManagement.wsHRIS.CompanyList request);
        
        // CODEGEN: Generating message contract since the wrapper name (DepartmentList) of message DepartmentList does not match the default value (getDepartment)
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/DepartmentList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraineeManagement.wsHRIS.DepartmentList1 getDepartment(TraineeManagement.wsHRIS.DepartmentList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/DepartmentList", ReplyAction="*")]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.DepartmentList1> getDepartmentAsync(TraineeManagement.wsHRIS.DepartmentList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getITOutsource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getITOutsource();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getITOutsource", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getITOutsourceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllRank", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllRank();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllRank", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllRankAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllRankJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllRankJob(string PoolID, string RankID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllRankJob", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllRankJobAsync(string PoolID, string RankID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllPool", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllPool();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllPool", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllPoolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllUnitGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllUnitGroup(string PoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllUnitGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllUnitGroupAsync(string PoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllUnit(string CompanyID, string PoolID, string UnitGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllUnitAsync(string CompanyID, string PoolID, string UnitGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllUnitGroupHead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllUnitGroupHead(string PoolID, string UnitGroupID, string ByRank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllUnitGroupHead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllUnitGroupHeadAsync(string PoolID, string UnitGroupID, string ByRank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllRoleHead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllRoleHead(string RoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllRoleHead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllRoleHeadAsync(string RoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllPoolHead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllPoolHead(string PoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/getAllPoolHead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllPoolHeadAsync(string PoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Get_Holiday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_Holiday(string Year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://th.kpmg.intranet/Get_Holiday", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_HolidayAsync(string Year);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_GetEmployeeDetailDataSet_No_Parameter", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_GetEmployeeDetailDataSet_No_Parameter {
        
        public WS_GetEmployeeDetailDataSet_No_Parameter() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_GetEmployeeDetailDataSet_No_ParameterResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_GetEmployeeDetailDataSet_No_Parameter1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet WS_GetEmployeeDetailDataSet_No_ParameterResult;
        
        public WS_GetEmployeeDetailDataSet_No_Parameter1() {
        }
        
        public WS_GetEmployeeDetailDataSet_No_Parameter1(System.Data.DataSet WS_GetEmployeeDetailDataSet_No_ParameterResult) {
            this.WS_GetEmployeeDetailDataSet_No_ParameterResult = WS_GetEmployeeDetailDataSet_No_ParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_GetEmployeeDetailDataSet_With_Parameter", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_GetEmployeeDetailDataSet_With_Parameter {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public string EmployeeNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=1)]
        public string ColumnName;
        
        public WS_GetEmployeeDetailDataSet_With_Parameter() {
        }
        
        public WS_GetEmployeeDetailDataSet_With_Parameter(string EmployeeNo, string ColumnName) {
            this.EmployeeNo = EmployeeNo;
            this.ColumnName = ColumnName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_GetEmployeeDetailDataSet_With_ParameterResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class WS_GetEmployeeDetailDataSet_With_Parameter1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet WS_GetEmployeeDetailDataSet_With_ParameterResult;
        
        public WS_GetEmployeeDetailDataSet_With_Parameter1() {
        }
        
        public WS_GetEmployeeDetailDataSet_With_Parameter1(System.Data.DataSet WS_GetEmployeeDetailDataSet_With_ParameterResult) {
            this.WS_GetEmployeeDetailDataSet_With_ParameterResult = WS_GetEmployeeDetailDataSet_With_ParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompanyList", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class CompanyList {
        
        public CompanyList() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompanyListResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class CompanyList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet CompanyListResult;
        
        public CompanyList1() {
        }
        
        public CompanyList1(System.Data.DataSet CompanyListResult) {
            this.CompanyListResult = CompanyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepartmentList", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class DepartmentList {
        
        public DepartmentList() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepartmentListResponse", WrapperNamespace="http://th.kpmg.intranet/", IsWrapped=true)]
    public partial class DepartmentList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://th.kpmg.intranet/", Order=0)]
        public System.Data.DataSet DepartmentListResult;
        
        public DepartmentList1() {
        }
        
        public DepartmentList1(System.Data.DataSet DepartmentListResult) {
            this.DepartmentListResult = DepartmentListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HRISSoapChannel : TraineeManagement.wsHRIS.HRISSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRISSoapClient : System.ServiceModel.ClientBase<TraineeManagement.wsHRIS.HRISSoap>, TraineeManagement.wsHRIS.HRISSoap {
        
        public HRISSoapClient() {
        }
        
        public HRISSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRISSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRISSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRISSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getEmployeeInfo(string empIdType, string empId, string active, string pool, string pi, string comp, string rank) {
            return base.Channel.getEmployeeInfo(empIdType, empId, active, pool, pi, comp, rank);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoAsync(string empIdType, string empId, string active, string pool, string pi, string comp, string rank) {
            return base.Channel.getEmployeeInfoAsync(empIdType, empId, active, pool, pi, comp, rank);
        }
        
        public System.Data.DataTable getCustomEmployeeInfo(string empIdType, string empId, string active, string pool, string pi, string comp, string rank, string unitgroup) {
            return base.Channel.getCustomEmployeeInfo(empIdType, empId, active, pool, pi, comp, rank, unitgroup);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getCustomEmployeeInfoAsync(string empIdType, string empId, string active, string pool, string pi, string comp, string rank, string unitgroup) {
            return base.Channel.getCustomEmployeeInfoAsync(empIdType, empId, active, pool, pi, comp, rank, unitgroup);
        }
        
        public System.Data.DataTable getAllActiveStaff() {
            return base.Channel.getAllActiveStaff();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllActiveStaffAsync() {
            return base.Channel.getAllActiveStaffAsync();
        }
        
        public System.Data.DataTable getAllStaff() {
            return base.Channel.getAllStaff();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllStaffAsync() {
            return base.Channel.getAllStaffAsync();
        }
        
        public System.Data.DataTable getActiveStaffByEmpNo(string empno) {
            return base.Channel.getActiveStaffByEmpNo(empno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getActiveStaffByEmpNoAsync(string empno) {
            return base.Channel.getActiveStaffByEmpNoAsync(empno);
        }
        
        public System.Data.DataTable getActiveStaffByUserID(string userid) {
            return base.Channel.getActiveStaffByUserID(userid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getActiveStaffByUserIDAsync(string userid) {
            return base.Channel.getActiveStaffByUserIDAsync(userid);
        }
        
        public System.Data.DataTable getEmployeeInfoByEmpNo(string empno) {
            return base.Channel.getEmployeeInfoByEmpNo(empno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoByEmpNoAsync(string empno) {
            return base.Channel.getEmployeeInfoByEmpNoAsync(empno);
        }
        
        public System.Data.DataTable getEmployeeInfoByEmpNoMultiple(string empno) {
            return base.Channel.getEmployeeInfoByEmpNoMultiple(empno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoByEmpNoMultipleAsync(string empno) {
            return base.Channel.getEmployeeInfoByEmpNoMultipleAsync(empno);
        }
        
        public System.Data.DataTable getEmployeeInfoByUserID(string userid) {
            return base.Channel.getEmployeeInfoByUserID(userid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeInfoByUserIDAsync(string userid) {
            return base.Channel.getEmployeeInfoByUserIDAsync(userid);
        }
        
        public string getEmployeeNoByUname(string uname) {
            return base.Channel.getEmployeeNoByUname(uname);
        }
        
        public System.Threading.Tasks.Task<string> getEmployeeNoByUnameAsync(string uname) {
            return base.Channel.getEmployeeNoByUnameAsync(uname);
        }
        
        public string getEmployeeName(string empIdType, string empId, bool middlename, bool prefix) {
            return base.Channel.getEmployeeName(empIdType, empId, middlename, prefix);
        }
        
        public System.Threading.Tasks.Task<string> getEmployeeNameAsync(string empIdType, string empId, bool middlename, bool prefix) {
            return base.Channel.getEmployeeNameAsync(empIdType, empId, middlename, prefix);
        }
        
        public string getEmployeeEmail(string empIdType, string empId) {
            return base.Channel.getEmployeeEmail(empIdType, empId);
        }
        
        public System.Threading.Tasks.Task<string> getEmployeeEmailAsync(string empIdType, string empId) {
            return base.Channel.getEmployeeEmailAsync(empIdType, empId);
        }
        
        public string getUserIDByEmployeeNo(string empNo) {
            return base.Channel.getUserIDByEmployeeNo(empNo);
        }
        
        public System.Threading.Tasks.Task<string> getUserIDByEmployeeNoAsync(string empNo) {
            return base.Channel.getUserIDByEmployeeNoAsync(empNo);
        }
        
        public string getEmployeeNoByUserID(string userID) {
            return base.Channel.getEmployeeNoByUserID(userID);
        }
        
        public System.Threading.Tasks.Task<string> getEmployeeNoByUserIDAsync(string userID) {
            return base.Channel.getEmployeeNoByUserIDAsync(userID);
        }
        
        public int isActiveEmployee(string empIdType, string empId) {
            return base.Channel.isActiveEmployee(empIdType, empId);
        }
        
        public System.Threading.Tasks.Task<int> isActiveEmployeeAsync(string empIdType, string empId) {
            return base.Channel.isActiveEmployeeAsync(empIdType, empId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter1 TraineeManagement.wsHRIS.HRISSoap.WS_GetEmployeeDetailDataSet(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter request) {
            return base.Channel.WS_GetEmployeeDetailDataSet(request);
        }
        
        public System.Data.DataSet WS_GetEmployeeDetailDataSet() {
            TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter inValue = new TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter();
            TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter1 retVal = ((TraineeManagement.wsHRIS.HRISSoap)(this)).WS_GetEmployeeDetailDataSet(inValue);
            return retVal.WS_GetEmployeeDetailDataSet_No_ParameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter1> TraineeManagement.wsHRIS.HRISSoap.WS_GetEmployeeDetailDataSetAsync(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter request) {
            return base.Channel.WS_GetEmployeeDetailDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter1> WS_GetEmployeeDetailDataSetAsync() {
            TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter inValue = new TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_No_Parameter();
            return ((TraineeManagement.wsHRIS.HRISSoap)(this)).WS_GetEmployeeDetailDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter1 TraineeManagement.wsHRIS.HRISSoap.WS_GetEmployeeDetailDataSet1(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter request) {
            return base.Channel.WS_GetEmployeeDetailDataSet1(request);
        }
        
        public System.Data.DataSet WS_GetEmployeeDetailDataSet1(string EmployeeNo, string ColumnName) {
            TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter inValue = new TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter();
            inValue.EmployeeNo = EmployeeNo;
            inValue.ColumnName = ColumnName;
            TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter1 retVal = ((TraineeManagement.wsHRIS.HRISSoap)(this)).WS_GetEmployeeDetailDataSet1(inValue);
            return retVal.WS_GetEmployeeDetailDataSet_With_ParameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter1> TraineeManagement.wsHRIS.HRISSoap.WS_GetEmployeeDetailDataSet1Async(TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter request) {
            return base.Channel.WS_GetEmployeeDetailDataSet1Async(request);
        }
        
        public System.Threading.Tasks.Task<TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter1> WS_GetEmployeeDetailDataSet1Async(string EmployeeNo, string ColumnName) {
            TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter inValue = new TraineeManagement.wsHRIS.WS_GetEmployeeDetailDataSet_With_Parameter();
            inValue.EmployeeNo = EmployeeNo;
            inValue.ColumnName = ColumnName;
            return ((TraineeManagement.wsHRIS.HRISSoap)(this)).WS_GetEmployeeDetailDataSet1Async(inValue);
        }
        
        public string WS_CheckActiveUser(string Param, string Type) {
            return base.Channel.WS_CheckActiveUser(Param, Type);
        }
        
        public System.Threading.Tasks.Task<string> WS_CheckActiveUserAsync(string Param, string Type) {
            return base.Channel.WS_CheckActiveUserAsync(Param, Type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraineeManagement.wsHRIS.CompanyList1 TraineeManagement.wsHRIS.HRISSoap.getCompany(TraineeManagement.wsHRIS.CompanyList request) {
            return base.Channel.getCompany(request);
        }
        
        public System.Data.DataSet getCompany() {
            TraineeManagement.wsHRIS.CompanyList inValue = new TraineeManagement.wsHRIS.CompanyList();
            TraineeManagement.wsHRIS.CompanyList1 retVal = ((TraineeManagement.wsHRIS.HRISSoap)(this)).getCompany(inValue);
            return retVal.CompanyListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.CompanyList1> TraineeManagement.wsHRIS.HRISSoap.getCompanyAsync(TraineeManagement.wsHRIS.CompanyList request) {
            return base.Channel.getCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraineeManagement.wsHRIS.CompanyList1> getCompanyAsync() {
            TraineeManagement.wsHRIS.CompanyList inValue = new TraineeManagement.wsHRIS.CompanyList();
            return ((TraineeManagement.wsHRIS.HRISSoap)(this)).getCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraineeManagement.wsHRIS.DepartmentList1 TraineeManagement.wsHRIS.HRISSoap.getDepartment(TraineeManagement.wsHRIS.DepartmentList request) {
            return base.Channel.getDepartment(request);
        }
        
        public System.Data.DataSet getDepartment() {
            TraineeManagement.wsHRIS.DepartmentList inValue = new TraineeManagement.wsHRIS.DepartmentList();
            TraineeManagement.wsHRIS.DepartmentList1 retVal = ((TraineeManagement.wsHRIS.HRISSoap)(this)).getDepartment(inValue);
            return retVal.DepartmentListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraineeManagement.wsHRIS.DepartmentList1> TraineeManagement.wsHRIS.HRISSoap.getDepartmentAsync(TraineeManagement.wsHRIS.DepartmentList request) {
            return base.Channel.getDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraineeManagement.wsHRIS.DepartmentList1> getDepartmentAsync() {
            TraineeManagement.wsHRIS.DepartmentList inValue = new TraineeManagement.wsHRIS.DepartmentList();
            return ((TraineeManagement.wsHRIS.HRISSoap)(this)).getDepartmentAsync(inValue);
        }
        
        public System.Data.DataSet getITOutsource() {
            return base.Channel.getITOutsource();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getITOutsourceAsync() {
            return base.Channel.getITOutsourceAsync();
        }
        
        public System.Data.DataTable getAllRank() {
            return base.Channel.getAllRank();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllRankAsync() {
            return base.Channel.getAllRankAsync();
        }
        
        public System.Data.DataTable getAllRankJob(string PoolID, string RankID) {
            return base.Channel.getAllRankJob(PoolID, RankID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllRankJobAsync(string PoolID, string RankID) {
            return base.Channel.getAllRankJobAsync(PoolID, RankID);
        }
        
        public System.Data.DataTable getAllPool() {
            return base.Channel.getAllPool();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllPoolAsync() {
            return base.Channel.getAllPoolAsync();
        }
        
        public System.Data.DataTable getAllUnitGroup(string PoolID) {
            return base.Channel.getAllUnitGroup(PoolID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllUnitGroupAsync(string PoolID) {
            return base.Channel.getAllUnitGroupAsync(PoolID);
        }
        
        public System.Data.DataTable getAllUnit(string CompanyID, string PoolID, string UnitGroupID) {
            return base.Channel.getAllUnit(CompanyID, PoolID, UnitGroupID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllUnitAsync(string CompanyID, string PoolID, string UnitGroupID) {
            return base.Channel.getAllUnitAsync(CompanyID, PoolID, UnitGroupID);
        }
        
        public System.Data.DataTable getAllUnitGroupHead(string PoolID, string UnitGroupID, string ByRank) {
            return base.Channel.getAllUnitGroupHead(PoolID, UnitGroupID, ByRank);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllUnitGroupHeadAsync(string PoolID, string UnitGroupID, string ByRank) {
            return base.Channel.getAllUnitGroupHeadAsync(PoolID, UnitGroupID, ByRank);
        }
        
        public System.Data.DataTable getAllRoleHead(string RoleID) {
            return base.Channel.getAllRoleHead(RoleID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllRoleHeadAsync(string RoleID) {
            return base.Channel.getAllRoleHeadAsync(RoleID);
        }
        
        public System.Data.DataTable getAllPoolHead(string PoolID) {
            return base.Channel.getAllPoolHead(PoolID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllPoolHeadAsync(string PoolID) {
            return base.Channel.getAllPoolHeadAsync(PoolID);
        }
        
        public System.Data.DataTable Get_Holiday(string Year) {
            return base.Channel.Get_Holiday(Year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_HolidayAsync(string Year) {
            return base.Channel.Get_HolidayAsync(Year);
        }
    }
}
